---
- name: Installer Node.js et npm

- name: Créer le répertoire de l'application

- name: Copier l'application app.js
  copy:
    src: "{{ playbook_dir }}/app.js"
    dest: "{{ app_dir }}/app.js"
    mode: '0755'

- name: Copier le fichier package.json

- name: Installer les dépendances Node.js
  command: npm install
  args:
    chdir: "{{ app_dir }}"

- name: Installer Express

- name: Recharger les unités systemd

- name: Créer le service systemd pour Node.js (Jinja 2)

